blog/urls.py
from django.urls import path

from . import views

# codestart:001
app_name = 'blog'
urlpatterns = [
    path('', views.default_view, name='default_view'),
    path('redirect', views.redirect_view, name='redirect_view'),
    path('<slug:author_name>/', views.BlogIndex.as_view(), name='index'),
    path('<slug:author_name>/<int:pk>/', views.BlogDetail.as_view(), name='detail'),
    path('<slug:author_name>/search', views.BlogSearch.as_view(), name='search'),

    path('<slug:author_name>/comment/<int:post_id>/', views.comment, name='comment'),
    path('<slug:author_name>/comment/<int:comment_id>/update', views.comment_update, name='comment_update'),
    path('<slug:author_name>/reply/<int:comment_id>/', views.reply, name='reply'),
]
# codeend:001

urlpatterns += [
    path('<slug:author_name>/<slug:template_name>/', views.BlogDetailTest.as_view(), name='detail_test'),
]

blog/forms.py
from django import forms
from . import models

# codestart:SearchForm
class SearchForm(forms.Form):
    keyword = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'id':'search-keyword',
            'class':'form-control',
        })
    )
# codeend:SearchForm

# codestart:CommentForm
class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['status'].required = False
        self.fields['status'].choices = models.CommentStatus.get_choices()
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = models.Comment
        fields = ('name_text', 'comment_text', 'status')
# codeend:CommentForm

blog/views/base.py
import logging
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import Http404
from django.http import JsonResponse
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext as _

from blog import models
from blog.lib import constants
from blog.lib import common
from blog.lib import utils

logger = logging.getLogger(__name__)

# codestart:redirect_view
def redirect_view(request):
    url = request.GET.get('url')
    if url:
        message = request.GET.get('message')
        if message:
            request.session[constants.SESSION_MESSAGES] = [
                {'level': int(request.GET.get('message_level', messages.INFO)),'message' :_(message)}
            ]
        return redirect(url)
    else:
        logger.error('Parameter Error')
        raise Http404
# codeend:redirect_view

# codestart:default_view
def default_view(request):
    if hasattr(settings, 'DEFAULT_AUTHOR') and settings.DEFAULT_AUTHOR:
        return redirect('blog:index', settings.DEFAULT_AUTHOR)
    else:
        logger.error('settings.DEFAULT_AUTHOR is not defined.')
        raise Http404
# codeend:default_view

# class CommonMixin(generic.base.TemplateResponseMixin):
# codestart:CommonMixin
class CommonMixin():
    def get_template_names(self):
        template = super().get_template_names()
        self.kwargs['base_template'] = template[0]
        language_codes = common.get_author_language_codes(self.kwargs['author'].id)
        self.kwargs['available_languages'] = utils.get_languages(self.request, language_codes)
        template[0] = utils.get_template_path(self.request, self.kwargs['author_name'], 'extends')
        logger.debug(f'{self.kwargs["base_template"]}:{template[0]}')
        return template
# codeend:CommonMixin

blog/views/comment.py
import logging
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext as _
from ipware import get_client_ip

from blog import forms
from blog import mails
from blog import models
from blog.lib import constants
from blog.lib import common

logger = logging.getLogger(__name__)

# codestart:comment
def comment(request, *args, **kwargs):
    post = get_object_or_404(models.Post, pk=kwargs['post_id'])
    if not post.is_comment or not post.is_comment_entry:
        raise PermissionDenied

    form = forms.CommentForm(request.POST or None)
    if not form.is_valid():
        return JsonResponse({
            'status': 11,
            'message': _('Input Error'),
        })
    
    comment = form.save(commit=False)
    comment.post = post
    comment.client_text = get_client_ip(request)[0]
    comment.save()

    mails.comment_notification(request, comment)
    logging.getLogger(constants.OPERATION_LOG).info({'post':post.id})
    return JsonResponse({
        'status': 1,
        'message': _('COMMENT_REGISTERED'),
    })
# codeend:comment

# codestart:reply
def reply(request, *args, **kwargs):
    parent = get_object_or_404(models.Comment, pk=kwargs['comment_id'])

    if not common.has_perm(request, constants.PERMISSION_COMMENT_REPLY, post=parent, author=kwargs['author']):
        raise PermissionDenied

    form = forms.CommentForm(request.POST or None)
    if not form.is_valid():
        return JsonResponse({
            'status': 11,
            'message': _('Input Error'),
        })
    
    comment = form.save(commit=False)
    comment.post = parent.post
    comment.parent = parent
    comment.client_text = get_client_ip(request)[0]
    comment.save()

    logging.getLogger(constants.OPERATION_LOG).info({'post':parent.post.id, 'parent':parent.id})
    return JsonResponse({
        'status': 1,
        'message': _('REPLY_REGISTERED'),
    })
# codeend:reply

# codestart:comment_update
def comment_update(request, *args, **kwargs):
    comment = get_object_or_404(models.Comment, pk=kwargs['comment_id'])
    if not common.has_perm(request, constants.PERMISSION_COMMENT_EDIT, post=comment.post, author=kwargs['author']):
        raise PermissionDenied
    form = forms.CommentForm(request.POST or None)
    status = form['status'].data
    if not status:
        return JsonResponse({
            'status': 11,
            'message': _('Input Error'),
        })
    comment.status = int(status)
    comment.save()
    
    logging.getLogger(constants.OPERATION_LOG).info({'post':comment.post.id, 'comment':comment.id})
    return JsonResponse({
        'status': 1,
        'data': {
            'status': comment.status,
            'status_name': str(models.CommentStatus(comment.status))
        },
        'message': _('COMMENT_UPDATED'),
    })
# codeend:comment_update

blog/views/detail.py
import logging
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.views import generic
from . import base
from blog import forms
from blog import models
from blog.lib import constants
from blog.lib import common
from blog.lib import utils

logger = logging.getLogger(__name__)

# codestart:BlogDetail
class BlogDetail(base.CommonMixin, generic.DetailView):
    model = models.Post

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.kwargs['author'].id)
        if not self.request.user.is_authenticated:
            queryset = queryset.filter(status__gte=models.PostStatus.PUBLIC)
        return queryset

    def get_object(self):
        obj = super().get_object()
        if not self.request.user.is_authenticated:
            obj.view_count += 1
            obj.save()
        obj.categories = list(obj.postcategory_set.all())
        obj.content = obj.postcontent_set.get(language_code=self.request.LANGUAGE_CODE,)
        comment_status = models.CommentStatus.UNAPPROVED if self.request.user.is_authenticated else models.CommentStatus.APPROVED
        if obj.is_comment:
            comments = list(obj.comment_set.filter(status__gte=comment_status))
            parents = []
            replydict = dict() 
            for comment in comments:
                comment.status_name = str(models.CommentStatus(comment.status))
                if comment.parent:
                    replies = replydict.get(comment.parent.id, [])
                    replies.append(comment)
                    replydict[comment.parent.id] = replies
                else:
                    parents.append(comment)
            for comment in parents:
                comment.replies = replydict.get(comment.id)
            obj.comments = parents
            obj.is_comment_edit = common.has_perm(
                self.request,
                constants.PERMISSION_COMMENT_EDIT,
                post=obj,
                author=self.kwargs['author']
            )
            obj.is_comment_reply = common.has_perm(
                self.request,
                constants.PERMISSION_COMMENT_REPLY,
                post=obj,
                author=self.kwargs['author']
            )
        self.template_name = utils.get_template_path(self.request, self.kwargs['author_name'], obj.template_text)
        return obj
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = forms.CommentForm(None)
        logging.getLogger(constants.OPERATION_LOG).info({'post':self.object.id})
        return context

    def get_template_names(self):
        template_names = super().get_template_names()
        language_codes = common.get_post_language_codes(self.object.id)
        self.kwargs['available_languages'] = utils.get_languages(self.request, language_codes)
        return template_names
# codeend:BlogDetail

class BlogDetailTest(generic.DetailView):
    model = models.Post
    template_name = 'blog/detail_test.html'

    def get_object(self):
        obj = models.Post()
        obj.id = 0
        obj.title_text = f'test {self.kwargs["author_name"]}/{self.kwargs["template_name"]}'
        obj.template_text = self.kwargs['template_name']
        obj.created_date = timezone.now()
        return obj
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['test_template'] = utils.get_template_path(self.request, self.kwargs['author_name'], self.object.template_text)
        return context

blog/views/list.py
import re
import logging
from django.db.models import Q
from django.utils.translation import ugettext as _
from django.views import generic

from blog import forms
from blog import models
from blog.lib import constants
from blog.lib import utils

from . import base

# codestart:BlogList
class BlogList(generic.ListView):
    model = models.PostContent
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(
                post__author=self.kwargs['author'].id,
                language_code=self.request.LANGUAGE_CODE,
            )
        if not self.request.user.is_authenticated:
            queryset = queryset.filter(post__status__gte=models.PostStatus.PUBLIC)
        return queryset.order_by('-post__view_count')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        object_list = context['object_list']
        for post_content in object_list:
            post_content.categories = list(post_content.post.postcategory_set.all())
        return context
# codeend:BlogList

# codestart:BlogIndex
class BlogIndex(base.CommonMixin, BlogList):
    template_name = 'blog/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        logging.getLogger(constants.OPERATION_LOG).info('')
        return context
# codeend:BlogIndex

# codestart:BlogSearch
class BlogSearch(base.CommonMixin, BlogList):
    template_name = 'blog/search.html'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.form = None

    def get_query(self, keyword):
        category_ids = []
        search_words = []
        category_keywords = re.findall(r'category:[^ 　]+', keyword)
        if category_keywords:
            for category_keyword in category_keywords:
                category_text = re.findall(r'category:([^ 　]+)', category_keyword)[0]
                category = models.Category.objects.get(author=self.kwargs['author'].id,category_text=category_text)
                if category:
                    category_ids.append(category.id)
                    keyword = keyword.replace(category_keyword, '').strip()
        
        if keyword:
            search_words = re.split(r'[ 　]+', keyword)

        queries = []
        category_ids = list(set(category_ids))
        if category_ids:
            queries.append(Q(post__postcategory__category_id__in=category_ids))

        search_words = list(set(search_words))
        if search_words:
            text_query = Q(search_text__contains=search_words.pop())
            for search_word in search_words:
                text_query &= Q(search_text__contains=search_word)
            queries.append(text_query)

        search_query = queries.pop()
        for query in queries:
            search_query &= query
        return search_query

    def get_queryset(self):
        self.form = forms.SearchForm(self.request.GET or None)
        queryset = super().get_queryset()
        if self.form.is_valid():
            keyword = self.form.cleaned_data['keyword'].strip()
            if (keyword):
                queryset = queryset.filter(self.get_query(keyword))
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form
        log_contents = {}
        if self.form.is_valid():
            log_contents['keyword'] = self.form.cleaned_data['keyword'].strip()
        logging.getLogger(constants.OPERATION_LOG).info(log_contents)
        return context
# codeend:BlogSearch

blog/templates/blog/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"ja" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="{% block meta_description %}{% endblock %}">
<link href="{% static 'apple-touch-icon.png' %}" rel="apple-touch-icon">
<link rel="icon" type="image/png" href="{% static 'android-touch-icon.png' %}" sizes="192x192">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block head_title %}{% endblock %}</title>
</head>
<body>
  <div>
    {% block main %}{% endblock %}
  </div>
  <footer class="blog-footer mt-5">
    {% block footer_text %}
      <p class="mb-0">2020 Tassk team</p>
    {% endblock %}
  </footer>
  <div id="alert_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="alert_container"></div>
      </div>
    </div>
  </div>
  <div id="overlay" style="display:none;">
    <div id="spinner">
      <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="{% static 'blog/js/script.js' %}"></script>
  <script>
    base = {
      redirect_url: "{% url 'blog:redirect_view' %}",
    };
  </script>
  {% block extra_js %}{% endblock %}
</body>
</html>

blog/templates/blog/blog_base.html
{% extends 'blog/base.html' %}
{% load i18n app_tags %}
{% block head_title %}{% block head_author_title %}{{ view.kwargs.author.title_text }}{% endblock %}{% endblock %}
{% block meta_description %}{% endblock %}
{% block main %}
  <div class="container">
    <header class="blog-header py-3">
      <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-6 pt-1">
          <a class="blog-header-logo text-dark" href="{% url 'blog:index' view.kwargs.author_name %}">{% block main_title %}{% block main_author_title %}{{ view.kwargs.author.title_text }}{% endblock %}{% endblock %}</a>
        </div>
        <div class="col-6 d-flex justify-content-end align-items-center">
          <div class="row w-100">
            <div class="col text-right" style="min-width:8rem;">
              <form action="{% url 'set_language' %}" method="POST">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}">
                {% if view.kwargs.available_languages %}
                  {% get_language_info_list for view.kwargs.available_languages as languages %}
                  {% if languages|length > 1 %}
                    <div class="input-group">
                      <select name="language" class="form-control">
                          {% get_current_language as LANGUAGE_CODE %}
                          {% for language in languages %}
                              <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                  {{ language.name_local }} ({{ language.code }})
                              </option>
                          {% endfor %}
                      </select>
                      <div class="input-group-append">
                        <input type="submit" class="btn btn-outline-secondary" value="Go">
                      </div>
                    </div>
                  {% else %}
                    <input type="submit" class="btn btn-light" value="{{ languages.0.name_local }}">
                    <input name="language" type="hidden" value="{{ languages.0.code }}">
                  {% endif %}
                {% endif %}
              </form>
            </div>
            <div class="col" style="min-width:8rem;">
              <form action="{% url 'blog:search' view.kwargs.author_name %}" method="GET">
                <input type="search" class="form-control ds-input" id="header-search" name="keyword" placeholder="Search..." autocomplete="off">
              </form>
          </div>
        </div>
      </div>
    </header>
  </div>
  <main class="container mt-3">
    <div class="row">
      <div class="col-md-8 blog-main">
        <div id="alert_container">
          {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" id="default_alert" role="alert">
              <div class="message-text">{{ message }}</div>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
          <div class="alert alert-dismissible fade show" id="default_alert" role="alert" style="display:none;">
            <div class="message-text"></div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
        {% block blog_main %}{% endblock %}
      </div>
      <aside class="col-md-4 blog-sidebar">
        <div class="position-sticky">
          {% block aside1 %}
            <div class="p-3 mb-3 bg-light rounded">
              <p class="mb-0">
                {% block author_aside %}{% endblock %}
              </p>
            </div>
          {% endblock %}
          {% block aside2 %}
            <div class="mb-3">
              {% category_summary view.kwargs.author.id %}
            </div>
          {% endblock %}
          {% block aside3 %}
            <div>
              {% post_favor view.kwargs.author.id 3 %}
            </div>
          {% endblock %}
        </div>
      </aside>
    </div>
  </main>
{% endblock %}

blog/templates/blog/blog_list.html
{% load i18n %}
{% if posts %}
  <ul class="list-group">
    {% for post_content in posts %}
      <li class="list-group-item">
        <h3 class="list-title">
          <a href="{% url 'blog:detail' view.kwargs.author_name post_content.post.id %}">{{ post_content.title_text }}</a>
        </h3>
        <div>
          {% for bc in post_content.categories %}
            <a href="#" data-category-text="{{ bc.category.category_text }}" class="category badge badge-light"><span>{{ bc.category.category_text }}</span></a>
          {% endfor %}
        </div>
        <p class="list-summary">{{ post_content.summary_text|truncatechars:100 }}</p>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>{% trans 'BLOG_NOTHING' %}</p>
{% endif %}

blog/templates/blog/detail.html
{# codestart:head #}
{% extends 'blog/blog_base.html' %}
{% load i18n static %}

{% block head_title %}{% block head_post_title %}{{ object.content.title_text }}{% endblock %} - {% block head_author_title %}{{ view.kwargs.author.title_text }}{% endblock %}{% endblock %}

{% block extra_css %}
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css">
{% endblock %}
{# codeend:head #}

{# codestart:blog_main #}
{% block blog_main %}
  <h1 class="mt-3">{% block post_title %}{{ object.content.title_text }}{% endblock %}</h1>
  <p class="ml-1 mb-0">
    <span class="post-created">{{ object.created_date|date:"Y/m/d" }}</span>
    <span class="post-updated">（{% trans 'Updated' %}:{{ object.updated_date|date:"Y/m/d" }}）</span>
  </p>
  <div>
    {% for bc in object.categories %}
      <a href="#" data-category-text="{{ bc.category.category_text }}" class="badge category badge-light"><span>{{ bc.category.category_text }}</span></a>
    {% endfor %}
  </div>
  <div class="mt-5">
    {% block post_content %}{% endblock %}
  </div>
  
  {% if object.is_comment %}
    <div>
      <h2>{% trans 'Comment' %}</h2>
      {% for comment in object.comments %}
        <div class="comment" data-id="{{ comment.id }}" data-status="{{ comment.status }}">
          <div>
            <div class="comment-summary">
              <span class="comment-name">{{ comment.name_text|default:'****' }}</span>
              <span class="comment-pipe">|</span>
              <span class="comment-created">{{ comment.created_date|date:"Y/m/d" }}</span>
              {% if request.user.is_authenticated %}
                <span class="comment-pipe">|</span>
                <span class="comment-status">{{ comment.status_name }}</span>
              {% endif %}
            </div>
            {% if request.user.is_authenticated %}
              <div class="float-right">
                {% if object.is_comment_edit %}
                  <button type="button" class="comment-edit btn btn-light">{% trans 'Edit' %}</button>
                {% endif %}
                {% if object.is_comment_reply %}
                  <button type="button" class="comment-reply btn btn-light">{% trans 'Reply' %}</button>
                {% endif %}
              </div>
            {% endif %}
          </div>
          {{ comment.comment_text|linebreaks }}

          {% if comment.replies %}
            <div class="reply-container ml-5">
              {% for reply in comment.replies %}
                  <div class="comment" data-id="{{ reply.id }}" data-status="{{ reply.status }}">
                    <div>
                      <div class="comment-summary">
                        <span class="comment-name">{{ reply.name_text|default:'****' }}</span>
                        <span class="comment-pipe">|</span>
                        <span class="comment-created">{{ reply.created_date|date:"Y/m/d" }}</span>
                        {% if request.user.is_authenticated %}
                          <span class="comment-pipe">|</span>
                          <span class="comment-status">{{ reply.status_name }}</span>
                        {% endif %}
                      </div>
                        <div class="float-right">
                          {% if object.is_comment_edit %}
                            <button type="button" class="comment-edit btn btn-light">{% trans 'Edit' %}</button>
                          {% endif %}
                          <button type="button" class="comment-reply btn btn-light invisible">{% trans 'Reply' %}</button>
                        </div>
                    </div>
                    {{ reply.comment_text|linebreaks }}
                  </div>
              {% endfor %}
            </div>
          {% endif %}

        </div>
      {% empty %}
        <p>{% trans 'COMMENT_NOTHING' %}</p>
      {% endfor %}
      {% if object.is_comment_entry %}
        <div class="mb-3">
          <button type="button" id="comment_entry" class="btn btn-light">{% trans 'Comment Entry' %}</button>
        </div>
      {% endif %}
    </div>
  {% endif %}
{# codeend:blog_main #}

  {# codestart:modal #}
  <div id="code_modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-xl">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="code-content">
            <div class="code-btn">
              <button type="button" id="code_modal_clipboard" alt="Copy to clipboard">Copy</button>
            </div>
            <div class="code-body">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% if object.is_comment %}
    <div id="comment_modal" class="modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">{% trans "Comment Entry" %}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="alert-container"></div>
            <div class="comment-wrapper"></div>
            <p id="comment_modal_message"></p>
            <form id="comment_form" action="{% url 'blog:comment' view.kwargs.author_name object.id %}" method="POST" onsubmit="return false;">
              <div class="form-group">
                <label for="name_text">{% trans 'Name' %}</label>
                <input type="text" id="name_text" name="name_text" placeholder="****">
              </div>
              <div class="form-group">
                <label for="comment_text">{% trans 'Comment' %}</label><span class="pl-1">*</span>
                <textarea id="comment_text" name="comment_text" class="form-control" rows="6"></textarea>
                <div class="text-right">
                  <span class="comment-length"><span id="comment_length">0</span>/1000</span>
                </div>
              </div>
              {% csrf_token %}
            </form>
            <p class="comment-note">
            {% trans "COMMENT_NOTE" %}
            </p>
          </div>
          <div class="modal-footer">
            <button type="button" id="comment_confirm" class="btn btn-primary">{% trans 'Confirm' %}</button>
            <button type="button" id="comment_back" class="btn btn-second">{% trans 'Back' %}</button>
            <button type="button" id="comment_save" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </div>
    </div>

    {% if object.is_comment_edit %}
      <div id="comment_edit_modal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">{% trans "Comment Edit" %}</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="comment-wrapper"></div>
              <form id="comment_edit_form" method="POST" onsubmit="return false;">
                <div class="form-group">
                  {{ comment_form.status }}
                </div>
                {% csrf_token %}
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" id="comment_update" class="btn btn-primary">{% trans 'Update' %}</button>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
  {% endif %}
  {# codeend:modal #}
{% endblock %}

{# codestart:script #}
{% block extra_js %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <script>
    $.extend(base, {
      detail: {
        actions: {
          comment: '{% url "blog:comment" view.kwargs.author_name object.id %}',
          reply: '{% url "blog:reply" view.kwargs.author_name 0 %}',
          comment_update: '{% url "blog:comment_update" view.kwargs.author_name 0 %}'
        },
        messages: {
          'Comment Entry': '{% trans "Comment Entry" %}',
          'Reply Entry': '{% trans "Reply Entry" %}',
          'COMMENT_ENTRY': '{% trans "COMMENT_ENTRY" %}',
          'COMMENT_CONFIRM': '{% trans "COMMENT_CONFIRM" %}'
        }
      }
    });
  </script>
  <script src="{% static 'blog/js/detail.js' %}"></script>
{% endblock %}
{# codeend:script #}